---

kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.0
          resources:
            requests:
              memory: "20Mi"
              cpu: "250m"
            limits:
              memory: "200Mi"
              cpu: "2"
          args:
            - --api.insecure
            - --entrypoints.web.Address=:80
            - --entrypoints.websecure.Address=:443
            - --providers.kubernetescrd
            - --certificatesResolvers.default.acme.email={{ acme_email }}
            - --certificatesResolvers.default.acme.storage=acme.json
            - --certificatesResolvers.default.acme.httpChallenge=true
            - --certificatesResolvers.default.acme.httpChallenge.entryPoint=web
          ports:
            - name: web
              containerPort: 8000
            - name: websecure
              containerPort: 4443
            - name: admin
              containerPort: 8080
