ignore:
  - "lib/aenum"
  - "lib/colorama"
  - "lib/h2"
  - "lib/hpack"
  - "lib/hyper"
  - "lib/hyperframe"
  - "lib/json_delta"
  - "lib/jsonpath_ng"
  - "lib/jwt"
  - "lib/ply"
  - "lib/pyaes"
  - "lib/rfc3986"
  - "lib/ipaddress.py"
  - "lib/six.py"
  - "lib/tabulate.py"
  - "lib/wmi.py"

coverage:
  status:
    patch: off
