image: python:3.9

stages:
  - test

run_sh_integration_tests:
  stage: test
  when: always
  before_script:
    - apt-get update
    - apt-get install -y libopenjp2-7
  script:
    - pip install -e .[DEV]
    - pytest -m "sh_integration"
