-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: flake8
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: end-of-file-fixer
        exclude: '^.+?\.json$'
-   repo: git://github.com/asottile/reorder_python_imports
    rev: v2.1.0
    hooks:
    -   id: reorder-python-imports
-   repo: git://github.com/pre-commit/mirrors-eslint
    sha: v3.14.0
    hooks:
    -   id: eslint
        additional_dependencies: ['eslint', 'eslint-plugin-html', 'eslint-config-airbnb', 'eslint-plugin-import', 'eslint-plugin-jsx-a11y']
