version: '3'

services:
  docs:
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    image: django_structlog_demo_project_docs
    volumes:
      - .:/app:cached
    command: /start
    environment:
      - SPHINX_COMMAND=html
    ports:
      - "5000:5000"
  docs-test:
    image: django_structlog_demo_project_docs
    volumes:
      - .:/app:cached
    command: /start
    environment:
      - SPHINX_COMMAND=doctest -E
