version: "2.1"
services:
    cardinal:
        container_name: cardinal
        build: .
        image: jmaguire/cardinal
        command: config/config.json
        volumes:
            - ./storage/:/usr/src/app/storage/
            - ./config/:/usr/src/app/config/
            - ./plugins/:/usr/src/app/plugins/
        restart: unless-stopped
