version: '2.4'

x-celery-fast: &celery-fast
  build:
    context: .
    dockerfile: ./docker_config/celery/Dockerfile.fast
    args:
      version: ${FORCAD_VERSION:-latest}

x-service-fast: &service-fast
  build:
    context: .
    dockerfile: ./docker_config/services/Dockerfile.fast
    args:
      version: ${FORCAD_VERSION:-latest}

services:
  celery:
    <<: *celery-fast

  celerybeat:
    <<: *celery-fast

  flower:
    <<: *celery-fast

  initializer:
    build:
      context: .
      dockerfile: ./docker_config/initializer/Dockerfile.fast
      args:
        version: ${FORCAD_VERSION:-latest}

  client_api:
    <<: *service-fast

  admin_api:
    <<: *service-fast

  events:
    <<: *service-fast

  monitoring:
    <<: *service-fast

  tcp_receiver:
    <<: *service-fast
