version: '2.4'

x-celery-test: &celery-test
  build:
    context: .
    dockerfile: ./docker_config/celery/Dockerfile.fast
    args:
      version: ${FORCAD_VERSION:-latest}
  restart: "no"

x-service-test: &service-test
  build:
    context: .
    dockerfile: ./docker_config/services/Dockerfile.fast
    args:
      version: ${FORCAD_VERSION:-latest}
  restart: "no"

services:
  celery:
    <<: *celery-test

  celerybeat:
    <<: *celery-test

  flower:
    <<: *celery-test

  initializer:
    build:
      context: .
      dockerfile: ./docker_config/initializer/Dockerfile.fast
      args:
        version: ${FORCAD_VERSION:-latest}
    restart: "no"

  client_api:
    <<: *service-test

  admin_api:
    <<: *service-test

  events:
    <<: *service-test

  monitoring:
    <<: *service-test

  tcp_receiver:
    <<: *service-test

  nginx:
    restart: "no"

  redis:
    restart: "no"

  postgres:
    restart: "no"

  rabbitmq:
    restart: "no"

  test_service:
    build:
      context: .
      dockerfile: ./docker_config/test_service/Dockerfile
    ports:
      - 10000:10000
    restart: "no"
