---

# Tasks to set up Traefik Ingress Controller in the cluster
# https://docs.traefik.io/user-guides/crd-acme/

# Custom resources

- name: Define custom resources
  k8s:
    state: present
    src: "files/traefik/{{ item }}.yml"
    validate:
      fail_on_error: yes
      strict: yes
  with_items:
    - ingress-route
    - ingress-route-tcp
    - middleware
    - tls-option

# RBAC

- name: Define RBAC resources
  k8s:
    state: present
    src: "files/traefik/{{ item }}.yml"
    validate:
      fail_on_error: yes
      strict: yes
  with_items:
    - cluster-role
    - cluster-role-binding

# Service

- name: Define service
  k8s:
    state: present
    src: files/traefik/service.yml
    validate:
      fail_on_error: yes
      strict: yes

# Ingress controller

- name: Define Ingress Service account
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        namespace: default
        name: traefik-ingress-controller
    validate:
      fail_on_error: yes
      strict: yes

- name: Define Ingress Controller
  k8s:
    state: present
    definition: "{{ lookup('template', 'files/traefik/deployment.yml') | from_yaml }}"
    validate:
      fail_on_error: yes
      strict: yes

# Set up the default A+ TLSOptions
- name: Configure TLS options
  k8s:
    state: present
    name: default
    namespace: default
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: TLSOption
      spec:
        minVersion: VersionTLS12
        cipherSuites:
          - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
          - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
          - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

# Set up the Traefik middlewares

- name: Configure SSL Redirect middleware
  k8s:
    state: present
    name: https-redirect
    namespace: default
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: Middleware
      spec:
        redirectScheme:
          scheme: https

- name: Configure HSTS middleware
  k8s:
    state: present
    name: https-hsts
    namespace: default
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: Middleware
      spec:
        headers:
          stsSeconds: 31536000
          stsIncludeSubdomains: yes
          stsPreload: yes
