---

- name: Create the NFS-server namespace
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: nfs-server
    validate:
      fail_on_error: yes
      strict: yes


- name: Create the NFS server deployment
  k8s:
    name: nfs-server
    namespace: nfs-server
    state: present
    definition:
      apiVersion: extensions/v1beta1
      kind: Deployment
      spec:
        replicas: 1
        selector:
          matchLabels:
            role: nfs-server
        template:
          metadata:
            labels:
              role: nfs-server
          spec:
            containers:
            - name: nfs-server
              image: gcr.io/google_containers/volume-nfs:0.8
              resources:
                requests:
                  memory: "200Mi"
                  cpu: "100m"
                limits:
                  memory: "500Mi"
                  cpu: "500m"
              ports:
                - name: nfs
                  containerPort: 2049
                - name: mountd
                  containerPort: 20048
                - name: rpcbind
                  containerPort: 111
              securityContext:
                privileged: true
              volumeMounts:
                - mountPath: /exports
                  name: pd-pvc
            volumes:
              - name: pd-pvc
                gcePersistentDisk:
                  pdName: "{{ disk_name }}"
                  fsType: ext4
    validate:
      fail_on_error: yes
      strict: yes

- name: Set up the NFS server service
  k8s:
    name: nfs-server
    namespace: nfs-server
    state: present
    definition:
      apiVersion: v1
      kind: Service
      spec:
        ports:
          - name: nfs
            port: 2049
          - name: mountd
            port: 20048
          - name: rpcbind
            port: 111
        selector:
          role: nfs-server
    validate:
      fail_on_error: yes
      strict: yes

- name: Provision the PV
  k8s:
    name: nfs
    namespace: nfs-server
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      spec:
        capacity:
          storage: "{{ disk_size }}"
        accessModes:
          - ReadWriteMany
        nfs:
          server: nfs-server.nfs-server.svc.cluster.local
          path: "/"
