---

- name: Deploy NLX on a single server
  hosts: all

  collections:
    - openzaak.deploy

  vars_files:
    - vars/postgres.yml
    - vars/open-zaak.yml
    - vars/nlx.yml

  vars:
    # postgresql vars - from secrets
    postgresql_users:
      - name: "{{ nlx_txlog_db_username }}"
        password: "{{ nlx_txlog_db_password }}"
        port: "{{ nlx_txlog_db_port }}"
      - name: "{{ nlx_txlog_db_username_api }}"
        password: "{{ nlx_txlog_db_password_api }}"
        port: "{{ nlx_txlog_db_port }}"
      - name: "{{ nlx_txlog_db_username_writer }}"
        password: "{{ nlx_txlog_db_password_writer }}"
        port: "{{ nlx_txlog_db_port }}"
    postgresql_databases:
      - name: "{{ nlx_txlog_db_name }}"
        owner: "{{ nlx_txlog_db_username }}"
        port: "{{ nlx_txlog_db_port }}"

  roles:

    - role: debian_setup

    - role: geerlingguy.postgresql
      tags:
        - db

    - role: geerlingguy.docker

    - role: nlx_docker
      vars:
        nlx_txdb_migrations_image: scrumteamzgw/txlog-db:latest  # fix with custom users/roles
      tags:
        - inway
        - outway
