---

apiVersion: v1
kind: Secret
metadata:
  name: "{{ item.name }}"
type: kubernetes.io/tls
data:
  tls.crt: "{{ lookup('file', item.certificate) | b64encode }}"
  tls.key: "{{ lookup('file', item.key) | b64encode }}"
