on: ["push", "pull_request"]

name: main workflow

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  linting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install Tox
      run: pip install tox

    - name: Run Tox
      run: tox -e lint

  py38core:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Setup Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install Tox
      run: pip install tox

    - name: Run Tox
      run: tox -e py38

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

  py37core:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install Tox
      run: pip install tox

    - name: Run Tox
      run: tox -e py37

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

  py36core:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Setup Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install Tox
      run: pip install tox

    - name: Run Tox
      run: tox -e py36

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
