name: Linux

# Run on PR requests. And on main itself.
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  TestLinux:
    name: Python ${{ matrix.python }} ${{ matrix.display_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python: 3.9
            numpy: "==1.12.*"
            pins: "pygdal==2.2.3.* scipy==0.19.* dask[delayed]==0.18.* pandas==0.19.* geopandas==0.4.1"
          - os: ubuntu-latest
            python: 3.9
            numpy: "==1.14.*"
            pins: "pygdal==2.2.3.* scipy==1.1.* dask[delayed]==0.20.* pandas==0.23.* geopandas==0.5.*"
          - os: ubuntu-latest
            python: 3.9
            numpy: "==1.16.*"
            pins: "pygdal==2.2.3.* scipy==1.3.* dask[delayed]==1.* pandas==0.25.* geopandas==0.6.*"
          - os: ubuntu-latest
            python: 3.9
            numpy: "==1.18.*"
            pins: "pygdal==3.0.4.* scipy==1.4.* dask[delayed]==2.9.* pandas==1.0.* geopandas==0.8.*"
          - os: ubuntu-latest
            python: 3.9
            numpy: "==1.20.*"
            pins: "pygdal==3.0.4.* scipy==1.6.* dask[delayed]==2020.* pandas==1.1.* geopandas==0.9.*"
          - os: ubuntu-latest
            python: 3.9
            display_name: "latest"
            pins: "pygdal==3.0.4.*"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install GDAL
        run: |
          sudo apt-get install --yes --no-install-recommends libgdal-dev

      - name: Install python dependencies
        shell: bash
        # NumPy is installed first because the pygdal build needs it.
        run: |
          pip install --disable-pip-version-check --upgrade pip setuptools wheel
          pip install numpy${{ matrix.numpy }}
          pip install -e .[test,cityhash] ${{ matrix.pins }}
          pip list

      - name: Run tests
        shell: bash
        run: |
          pytest dask_geomodeling
