# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies.
        run: |
          pip install coverage
          pip install codecov
          pip install pycodestyle
          pip install GPy
          pip install GPyOpt
          pip install pandas
          pip install nose

      - name: Install GADMA.
        run: |
          ./install
          cat gadma/version.py

      - name: Check code style.
        run: pycodestyle gadma

      - name: Run tests and codecov.
        run: |
          nosetests -vs tests --with-coverage --cover-package gadma     --cover-branches --cover-erase --cover-xml --cover-inclusive tests
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests

