name: Build

on:
  push:
    tags:
    - 'v*'

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, macOS-10.15]
        python-version: ["3.9", "3.10"]

    env:
      CIBW_SKIP: ?p27-*
      CIBW_BUILD_VERBOSITY: 3
      BUILD_OUTPUT_PATH: wheelhouse

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=stable
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.10.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir "$BUILD_OUTPUT_PATH"

      - uses: actions/upload-artifact@v4
        with:
          path: "./$BUILD_OUTPUT_PATH/*.whl"
