name: unit-tests
on: [push, pull_request]
jobs:
  OS:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - ubuntu:devel
          - ubuntu:rolling
          - ubuntu:latest
          - fedora:latest
          - fedora:rawhide

    timeout-minutes: 30
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Run unit tests
        # run as root; current Ubuntu podman breaks user networking ("could not find slirp4netns")
        run: sudo tests/run ${{ matrix.scenario }}
