name: tests
on:
  push:
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "static/**"
  pull_request:
    branches:
      - main

jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-latest
        test_type:
          - BLITZ
          - CLASSIC

    runs-on: ${{ matrix.os }}
    env:
      TEST: 1
      TEST_TYPE: ${{ matrix.test_type }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Setup tests
        run: python tests/setup_forcad.py
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r tests/requirements.txt
          pip install -r backend/requirements.txt
      - name: Setup ForcAD
        run: ./control.py setup
      - name: Build ForcAD
        run: ./control.py build

      - name: Start & run tests
        run: |
          export $(find ./docker_config -name "*.env" -exec egrep -v '^#' {} \; | xargs)
          ./control.py start
          python tests/wait_for_start.py
          ./control.py rd -c "ps"
          env | sort
          python -m unittest discover -v -s tests

      - name: Show logs
        if: ${{ failure() }}
        run: ./control.py rd -c "logs -f --tail 2000"

  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install requirements
        run: pip install -r tests/requirements.txt
      - name: Run flake
        run: ./control.py flake
