name: Unit test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v1
      - name: add symlink dir to PATH
        run: echo "::add-path::$HOME/.local/bin"
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      - name: Test jill download and install
        run: |
          make test

      - name: Test jill upstream
        run: |
          coverage run -a -m jill upstream

      - name: Test jill update
        run: |
          coverage run -a -m jill update
          coverage run -a -m jill update --upstream Official

      - name: generate covrage report
        run: |
          coverage report
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
