name: Test
on:
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10"]
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }} "
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Requirements
        run: |
          python -m pip install -U tox
      - name: Run Linting
        # only lint on 3.8 for two reasons
        #  1. faster overall runs
        #  2. Linting fails on py3.5 because tools require 3.6+
        if: ${{ matrix.python-version == '3.8' }}
        run: python -m tox -e lint
      - name: Run Tests
        run: python -m tox -e py
      - name: Ensure docs build
        # docs are only ever built on a linux 3.8 box (readthedocs)
        if: ${{ matrix.python-version == '3.8' && matrix.os == 'ubuntu-latest' }}
        run: python -m tox -e docs
