name: Run tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
        with-extension: ['0', '1']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coveralls pytest
        python setup.py develop
    - name: Run tests
      env:
        WITHOUT_EXTENSION: ${{ matrix.with-extension }}
      run: |
        coverage run --source=mwparserfromhell -m pytest
    - name: Submit to coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coveralls --service=github
