name: Sciris CI workflow
on: [pull_request]

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        python-version: ["3.9", "3.10"]
    name: Install and test
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Sciris
        run: python setup.py develop
      - name: Install tests
        run: pip install pytest
      - name: Run API tests
        working-directory: ./tests
        run: pytest test_*.py --durations=0 --junitxml=test-results.xml # Run actual tests
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test_results
          path: tests/test-results.xml
