name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install requirements and Run Tests
      run: make test

    - name: Run Coverage
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
