name: Run Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements/dev .
    
    - name: Launch tests
      run: |
        pytest --cov=checkQC --cov-report=xml tests/
    
    - name: Update data on codecov
      uses: codecov/codecov-action@v3
