# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test build and run tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  tests-py2:
    name: Runs tests that require python 2
    runs-on: ubuntu-latest
    container:
      image: python:3.9.18-buster

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    # - name: Set up Python 2.7
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: "3.9"
    - name: Test by decompiling a script and building un.rpyc
      run: |
        ./unrpyc.py --clobber testcases/script.rpyc
        diff -u testcases/script.orig.rpy testcases/script.rpy
        cd un.rpyc;
        ./compile.py -p 1
        cd ..
