name: build

on: [push, pull_request]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9", "3.10"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      env:
        KEY_MODELLER: ${{ secrets.KEY_MODELLER }}
      run: |
        tools/install_deps.sh ~/deps ${{ matrix.python-version }}
    - name: Test
      run: |
        export PATH=~/deps/bin:$PATH
        eval "$(conda shell.bash hook)"
        conda activate python${{ matrix.python-version }}
        make
        py.test --cov=. --cov-branch --cov-report=xml -v .
    - uses: codecov/codecov-action@v1
