name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  default:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt install -y pandoc
        python -m pip install --upgrade pip
        # Keep track of pyro-api main branch
        pip install https://github.com/pyro-ppl/pyro-api/archive/main.zip
        pip install .[test]
        pip freeze
    - name: Run test
      run: |
        make test


  torch:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Keep track of pyro-api main branch
        pip install https://github.com/pyro-ppl/pyro-api/archive/main.zip
        pip install torch==1.7.0+cpu torchvision==0.8.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
        # Keep track of Pyro main branch
        pip install https://github.com/pyro-ppl/pyro/archive/main.zip
        pip install .[test,torch]
        pip freeze
    - name: Run test
      run: |
        make test
        FUNSOR_BACKEND=torch make test


  jax:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Keep track of pyro-api main branch
        pip install https://github.com/pyro-ppl/pyro-api/archive/main.zip
        # Keep track of NumPyro main branch
        pip install https://github.com/pyro-ppl/numpyro/archive/main.zip
        pip install .[test,jax]
        pip freeze
    - name: Run test
      run: |
        CI=1 FUNSOR_BACKEND=jax make test
