on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
name: Continuous Integration
jobs:
  main:
    name: base
    strategy:
      matrix:
        python: ["3.9", "3.10"]
        os:
          - ubuntu-latest
        architecture:
          - x64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install requirements
        run: |
          pip install mypy flake8 -r requirements.txt

      - name: Run mypy typing checks
        run: |
          mypy chisel

      - name: Run flake8 formatting checks
        run: |
          flake8 chisel